on:
  workflow_dispatch:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  build-storybook:
    name: Build storybook
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js version 16.x
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm i -g yarn

      # Build docs
      - name: Docs build
        run: yarn docs:build:${{ inputs.configuration }}

      # Cache results
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: documentation
          key: ${{ runner.os }}-docs-build-${{ github.run_id }

