on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js version 16.x
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm i -g yarn

      # Run unit tests
      - name: Unit tests
        run: yarn unit:build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests
          path: coverage

