name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Default first step do checkout the repository
      - uses: actions/checkout@v3

      # Node js installation
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      # Protoc installation
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install yarn
      - name: Install yarn
        run: npm i -g yarn

      # Install dependencies
      - name: Install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install

      # Build
      - name: Build Typescript libraries âš™ï¸
        run: >
          find ./proto -iname "*.proto" | xargs -L 1 -d '\n'
          protoc
          -I=./proto
          --plugin="protoc-gen-ts=./node_modules/.bin/protoc-gen-ts"
          --ts_out=dist

      - name: Deploy to new branch ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: build-typescript
          folder: dist