name: deploy

on:
  push:
    branches: [master]
    paths: ['proto/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Default first step do checkout the repository
      - uses: actions/checkout@v3

      # Node js installation
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      
      # Protoc installation
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install yarn
      - name: Install yarn
        run: npm i -g yarn

      # Install dependencies
      - name: Install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install

      # Build
      - name: Build proto libraries âš™ï¸
        run: >
          find ./proto -iname "*.proto" | xargs -L 1 -d '\n'
          protoc
          -I=./proto
          --plugin="protoc-gen-ts=./node_modules/.bin/protoc-gen-ts"
          --ts_out=dist/typescript
          --java_out=dist/java

      # Deploy Typescript
      - name: Deploy TypeScript ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: build-typescript
          folder: dist/typescript

      # Deploy Java
      - name: Deploy Java ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: build-java
          folder: dist/java

  publish:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:

      # Default first step do checkout the repository
      - uses: actions/checkout@v3

      # Node js installation
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          always-auth: true

      # Public package
      - name: Publish package ðŸ“¦
        run: |
          git config --global user.name 'Vernite'
          git config --global user.email 'version-bump@vernite.dev'
          cd dist/typescript
          yarn version --patch
          yarn publish --access public
          cd ../..
          git push
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
