name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Default first step do checkout the repository
      - uses: actions/checkout@v3

      # Node js installation
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node modules
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      # Install yarn
      - name: Install yarn
        run: npm i -g yarn

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build
      - name: Build ðŸª›
        run: yarn build

      # Run tests
      - name: Unit tests
        run: yarn build:test

      # Build documentation and badges
      - name: Documentation
        run: |
          yarn build:docs
          yarn build:badges

      # Copy default redirect page
      - name: Redirect page copy
        run: cp src/redirect.html dist/workflow/index.html

      # Copy coverage directory
      - name: Copy coverage directory
        run: cp -R coverage documentation/coverage

      # Deploy to the server using rsync
      - name: Deploy app ðŸš€
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./dist/workflow/"
          REMOTE_HOST: '51.77.50.209'
          REMOTE_PORT: '2224'
          REMOTE_USER: 'frontend'
          TARGET: '/var/www/html'
          EXCLUDE: "/dist/, /node_modules/"

      # Deploy documentation to Github pages
      - name: Deploy documentation ðŸ—Ž
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: documentation
